# Generated by Django 4.2.10 on 2024-02-21 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appartments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apptype',
            name='koda',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='apptype',
            name='opis',
            field=models.TextField(blank=True, null=True),
        ),
    ]
